CREATE PROCEDURE P_CLIENTES_RECURRENTES(@LIMITE INT)
AS
SELECT		TOP(@LIMITE)
			UDE.PRC_USUARIO,
			CONCAT(LEFT(UDE.NOMBRE,1),'. ',UDE.APELLIDO)     AS CLIENTE,
			COUNT(OID.PC_ORDEN)								 AS NUM_ORDENES
FROM		OT_IDENTIFICACION OID
INNER JOIN	UT_CUENTA      UCU ON UCU.PC_CUENTA   = OID.RC_CLIENTE
INNER JOIN  UT_DESCRIPCION UDE ON UDE.PRC_USUARIO = UCU.PC_CUENTA
GROUP BY	UDE.PRC_USUARIO,
			UDE.NOMBRE,
			UDE.APELLIDO
ORDER BY	NUM_ORDENES DESC
GO

EXEC P_CLIENTES_RECURRENTES 1
GO