//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_AMABISCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BT_DESCRIPCION
    {
        public int PC_BAJA { get; set; }
        public int CANTIDAD { get; set; }
        public decimal PRECIO { get; set; }
        public string DETALLE { get; set; }
        public System.DateTime F_CREACION { get; set; }
        public int RC_PRODUCTO { get; set; }
        public int RC_TIPO { get; set; }
    
        public virtual PT_DESCRIPCION PT_DESCRIPCION { get; set; }
        public virtual BT_TIPO BT_TIPO { get; set; }
    }
}
