//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_AMABISCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_DESCRIPCION
    {
        public int PRC_ORDEN { get; set; }
        public int PRC_PRODUCTO { get; set; }
        public string CONDICION { get; set; }
        public int CANTIDAD { get; set; }
        public decimal PRECIO { get; set; }
    
        public virtual OT_IDENTIFICACION OT_IDENTIFICACION { get; set; }
        public virtual PT_DESCRIPCION PT_DESCRIPCION { get; set; }
    }
}
