//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_AMABISCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_IDENTIFICACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OT_IDENTIFICACION()
        {
            this.OT_DESCRIPCION = new HashSet<OT_DESCRIPCION>();
        }
    
        public int PC_ORDEN { get; set; }
        public System.DateTime F_EMISION { get; set; }
        public int RC_CLIENTE { get; set; }
        public int RC_EMISOR { get; set; }
        public string RC_ESTADO { get; set; }
        public string RC_ENVIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OT_DESCRIPCION> OT_DESCRIPCION { get; set; }
        public virtual OT_ENVIO OT_ENVIO { get; set; }
        public virtual OT_ESTADO OT_ESTADO { get; set; }
        public virtual UT_CUENTA UT_CUENTA { get; set; }
        public virtual UT_CUENTA UT_CUENTA1 { get; set; }
    }
}
