//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_AMABISCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PT_DESCRIPCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PT_DESCRIPCION()
        {
            this.AT_DESCRIPCION = new HashSet<AT_DESCRIPCION>();
            this.BT_DESCRIPCION = new HashSet<BT_DESCRIPCION>();
            this.IT_DESCRIPCION = new HashSet<IT_DESCRIPCION>();
            this.OT_DESCRIPCION = new HashSet<OT_DESCRIPCION>();
            this.PT_CATEGORIA = new HashSet<PT_CATEGORIA>();
        }
    
        public int PC_PRODUCTO { get; set; }
        public string NOMBRE { get; set; }
        public decimal PRECIO { get; set; }
        public string DESCRIPCION { get; set; }
        public byte[] IMAGEN { get; set; }
        public int CANTIDAD { get; set; }
        public string RC_UNIDAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AT_DESCRIPCION> AT_DESCRIPCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BT_DESCRIPCION> BT_DESCRIPCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IT_DESCRIPCION> IT_DESCRIPCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OT_DESCRIPCION> OT_DESCRIPCION { get; set; }
        public virtual PT_UNIDAD PT_UNIDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PT_CATEGORIA> PT_CATEGORIA { get; set; }
    }
}
