//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_AMABISCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_CUENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UT_CUENTA()
        {
            this.OT_IDENTIFICACION = new HashSet<OT_IDENTIFICACION>();
            this.OT_IDENTIFICACION1 = new HashSet<OT_IDENTIFICACION>();
        }
    
        public int PC_CUENTA { get; set; }
        public string NOMBRE { get; set; }
        public string CLAVE { get; set; }
        public int RC_ROL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OT_IDENTIFICACION> OT_IDENTIFICACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OT_IDENTIFICACION> OT_IDENTIFICACION1 { get; set; }
        public virtual UT_ROL UT_ROL { get; set; }
        public virtual UT_DESCRIPCION UT_DESCRIPCION { get; set; }
    }
}
